
name: from-fanza
dependencies:
- base
- text
- bytestring
- mtl
- webdriver
- hspec

library:
  source-dirs: src

executables:
  from-fanza-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - from-fanza

tests:
  from-fanza-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - from-fanza

